### ISSUE TITLE
issue with installing package

### ISSUE THREAD

**Issue by arthurcolle** [0mkara/etheratom#36]
➜  etheratom git:(master) npm --version
4.5.0
➜  etheratom git:(master) node --version
v7.9.0

```
➜  etheratom git:(master) apm install
Installing modules ✗
> scrypt@6.0.3 preinstall /Users/arthur/etheratom/node_modules/.staging/scrypt-27fd8500
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /Users/arthur/etheratom/node_modules/scrypt
> node-gyp rebuild

etheratom@4.0.0 /Users/arthur/etheratom
└── (empty)


gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/arthur/etheratom/node_modules/scrypt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Darwin 16.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/arthur/.atom/.apm/.apmrc" "--userconfig" "/Users/arthur/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.13" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arthur/etheratom/npm-debug.log
npm ERR! code 1
```

My Atom version is 1.16.0 - it is the most updated version of Atom. How are you getting this package to work? I can see that its using an older version of npm above, which I'm guessing is the problem:
```
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/arthur/.atom/.apm/.apmrc" "--userconfig" "/Users/arthur/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.13" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
```
Any ideas?
Thanks buddy

**Comment by 0mkara** [comment]
`node-gyp rebuild` used to create problem in linux as well but it is solved now. Can you please try `apm install etheratom` from shell ? I don't have any option to check it on Mac. Hope running installation from shell works.

**Comment by arthurcolle** [comment]
nah i've tried that, doesnt work. just got this computer two months ago and decided to usher in the new year with a default installation of python 3.5 instead of ever using python 2 again and looks like node-gyp still doesn't support python 3. very silly.

i don't see an easy solution other than to change my env to match what it needs. do you have any python3 installed?

**Comment by 0mkara** [comment]
No I don't have python 3 installed. I will try with that too. I do get `node node-scrypt-preinstall.js` error while installing it from atom editor but don't get it when I tried it from console. This `node-scrypt` error is pretty annoying.

**Comment by arthurcolle** [comment]
since I use the anaconda distribution for python 3, I am attempting to install the python 2 distribution as well. might be clashing because of anaconda specific things. 

had another question - to get this up and running, i just commented out the entirety of the python_interceptor.sh script and replaced it with `python2.7` which works fine as a hack in the interim. after running parity against the testnet, i can see the upper right hand corner menu with the ethereum options seems to pick up my account's address in the running parity client, but unfortunately the "unlock" button when i type in my password doesn't seem to be working. can you clarify how this behavior works for you? i don't use geth as i dont have the requisite space on this machine to keep a full copy of the testnet, so i use parity as an alternative as i can use the --warp feature. do you know if atom/your package listens for any keyups/keydowns and then ungreys itself as to indicate that the button can be clicked once the correct password has been typed in, or what? or do you think this is related to my usage of parity as opposed to geth?
 
thanks for the quick response here, appreciate the help.

**Comment by 0mkara** [comment]
Please check this before you start playing with python -
 https://ethereum.stackexchange.com/questions/12560/testrpc-install-on-osx-with-node-gyp-error
I think python has nothing to do with it.

**Comment by 0mkara** [comment]
Once you type the password and hit the unlock button etheratom package uses your password to unlock accounts whenever needed. I should add some animation to indicate that the password is accepted.

**Comment by 0mkara** [comment]
Install fails on linux when installing from atom editor
```
Installing â€œetheratom@3.0.0â€ failed.Hide outputâ€¦
/bin/bash: module: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for `BASH_FUNC_module'
/bin/bash: scl: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for `BASH_FUNC_scl'


> scrypt@6.0.3 preinstall /tmp/apm-install-dir-117323-17843-1pdbcyw/node_modules/.staging/scrypt-a57e89c0
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /tmp/apm-install-dir-117323-17843-1pdbcyw/node_modules/etheratom/node_modules/scrypt
> node-gyp rebuild

/tmp/apm-install-dir-117323-17843-1pdbcyw
â””â”€â”€ (empty)


(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
/bin/bash: scl: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for `BASH_FUNC_scl'
/bin/bash: module: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for `BASH_FUNC_module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.10-100.fc24.x86_64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-117323-17843-1pdbcyw/node_modules/etheratom/node_modules/scrypt
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117323-17843-1pdbcyw/package.json'
npm WARN apm-install-dir-117323-17843-1pdbcyw No description
npm WARN apm-install-dir-117323-17843-1pdbcyw No repository field.
npm WARN apm-install-dir-117323-17843-1pdbcyw No README data
npm WARN apm-install-dir-117323-17843-1pdbcyw No license field.
npm ERR! Linux 4.10.10-100.fc24.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/0mkar/.atom/.apm/.apmrc" "--userconfig" "/home/0mkar/.atom/.apmrc" "install" "/tmp/d-117323-17843-8c38oz/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117323-17843-1pdbcyw/npm-debug.log
npm ERR! code 1
```

**Comment by nickgs** [comment]
I experienced the same and messed around with this for a little bit. I fixed it by editing the file referenced in the error:

`/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh`

I changed the references to python to the explicit path to my python2 executable. Not a clean solution but it worked. 

This is definitely an environment issue. I use miniconda to manage different python environments.

**Comment by 0mkara** [comment]
@arthurcolle now 'unlock' button responses with color changes. Please update to v3.0.1.

**Comment by arthurcolle** [comment]
thanks boss

**Comment by 0mkara** [comment]
whoever is having installation issue can lookup here for solution - https://github.com/phusion/node-sha3/issues/27

**Comment by 0mkara** [comment]
Installing node v8.1.2 solved this issue for me. @arthurcolle @nickgs let me know if upgrading your node works.

**Comment by arthurcolle** [comment]
sweet ill try this now and report back

**Comment by akadatsky** [comment]
Faced with the same issue, 

> sudo apt-get install build-essential

Solution from https://github.com/phusion/node-sha3/issues/27 works

**Comment by ravijanrao** [comment]
For those of you on macs- I solved this issue by creating a virtual environment with python version 2.7 in the command line
`conda create -n py27 python=2.7 anaconda`
Then just activate this environment containing this python version with
`source activate py27`
Hopefully you'll see the brackets with (py27) on the side, then all I did was
`apm install etheratom`
And it worked for me. I spent a day or so trying to figure this out, hopefully this can help some others as well!

**Comment by Tomasvrba** [comment]
Hi all, having the same issue. Etheratom used to run fine for me and today it stopped working with:
"Failed to activate the etheratom package
soljson.cwrap is not a function"

```
apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.5.2
git 2.7.4
```


```
> sha3@1.2.0 install /tmp/apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i/node_modules/etheratom/node_modules/sha3
> node-gyp rebuild

/tmp/apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i
└── (empty)


npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/opt/atom/resources/app/apm/bin/python-interceptor.sh" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/opt/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /opt/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.4.0-96-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i/node_modules/etheratom/node_modules/sha3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i/package.json'
npm WARN apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i No description
npm WARN apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i No repository field.
npm WARN apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i No README data
npm WARN apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i No license field.
npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/tom/.atom/.apm/.apmrc" "--userconfig" "/home/tom/.atom/.apmrc" "install" "/tmp/d-11794-8365-1stoc0x.9ko30g4x6r/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11794-8365-jf5tgq.x74m5i2j4i/npm-debug.log
npm ERR! code 1


```

Any help is greatly appreciated! :)

**Comment by 0mkara** [comment]
@Tomasvrba your system upgraded to python 3.5.2 somehow. I imagine that started the problem. You have to try solutions mentioned above to resolve this problem with your system.

**Comment by Tomasvrba** [comment]
Thanks, I will give that a try

**Comment by wtlife** [comment]
I also encountered a similar problem, etheratom always installed failed, Any help is greatly appreciated!

`TypeError: soljson.cwrap is not a function
    at setupMethods (/home/wtlife/node_modules/_solc@0.4.17@solc/wrapper.js:7:29)
    at Object.<anonymous> (/home/wtlife/node_modules/_solc@0.4.17@solc/index.js:3:18)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/wtlife/etheratom/lib/vm/vm.js:8:20)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.loadVM (/home/wtlife/etheratom/lib/ethereum-interface.js:55:21)
    at Object.load (/home/wtlife/etheratom/lib/ethereum-interface.js:47:8)
    at Object.activate (/home/wtlife/etheratom/lib/ethereum-interface.js:34:8)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:218:19)
    at /usr/share/atom/resources/app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app.asar/src/package-manager.js:581:36)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:512:17`

`apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4
`

**Comment by 0mkara** [comment]
@wtlife can you please try command line installer apm to install the package ? Also try updating your node version.

**Comment by wtlife** [comment]
@0mkara I have updated the node to v8.1.2, and try 

`apm install etheratom` ,   i got 

> Installing etheratom to /home/wtlife/.atom/packages ✓

But when I open the atom , I get the error like this : 

`Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
Hide Stack Trace
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Object.cwrap (/home/wtlife/.atom/packages/etheratom/node_modules/rustbn.js/lib/index.asm.js:1:10888)
    at Object.<anonymous> (/home/wtlife/.atom/packages/etheratom/node_modules/ethereumjs-vm/lib/precompiled/06-ecadd.js:7:37)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/wtlife/.atom/packages/etheratom/node_modules/ethereumjs-vm/lib/index.js:15:15)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/wtlife/.atom/packages/etheratom/node_modules/ethereumjs-vm/index.js:1:97)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/wtlife/.atom/packages/etheratom/lib/vm/view.js:15:21)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)`

**Comment by Asurari30** [comment]
i need to install python to get etheratom?

**Comment by 0mkara** [comment]
https://github.com/AtomLinter/linter-puppet-lint/issues/68

This is a similar issue and as @tkdchen said

> My way without the need of removing environment-modules is to start atom from command line, for example,

```
cd path/to/project
atom .
```

Worked for me as well

**Comment by ezak** [comment]
I had python 3.5 on my path, I changed my path to python 2.7 and worked like a charm. 
the error clearly states that: 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.5.2, which is not supported by gyp.

**Comment by raininja** [comment]
One can simply set python as python2.7 in the apm config
```
[raijin@ishtar][~]%apm config set python python2.7
[raijin@ishtar][~]%apm config get
; cli configs
globalconfig = "/home/raijin/.atom/.apm/.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 linux x64"
userconfig = "/home/raijin/.atom/.apmrc"

; environment configs
node-gyp = "/usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp"

; userconfig /home/raijin/.atom/.apmrc
python = "python2.7"

; globalconfig /home/raijin/.atom/.apm/.apmrc
cache = "/home/raijin/.atom/.apm"
progress = false

; node bin location = /usr/share/atom/resources/app/apm/bin/node
; cwd = /home/raijin
; HOME = /home/raijin/.atom/.node-gyp
; "npm config ls -l" to show all defaults.

**Comment by 0mkara** [comment]
@raininja will it be possible to add this config to `package.json` or add some script to do it by the  package itself? If possible can you please try creating a PR ?
